server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_vary on;
    gzip_min_length 512;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:html|js|css)$ {
        add_header Cache-Control "no-cache";
    }

    location /images/opt/ {
        add_header Cache-Control "public, max-age=2592000";
    }

    location /typefaces/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
