// Generated by scripts/build-images.mjs — do not edit by hand.
const imageManifest = {
  "80srunning.webp": {
    "base": "80srunning",
    "w": 1080,
    "h": 1920,
    "tiers": [
      320,
      608,
      1080
    ],
    "srcKey": "1982754:1784148460524"
  },
  "running_playground.png": {
    "base": "running_playground",
    "w": 5896,
    "h": 3712,
    "tiers": [
      768,
      1504,
      3008,
      5896
    ],
    "srcKey": "536772:1784153443602"
  },
  "HC_Running_2.webp": {
    "base": "HC_Running_2",
    "w": 2250,
    "h": 2813,
    "tiers": [
      320,
      608,
      1216,
      2250
    ],
    "srcKey": "3174864:1784149410586"
  },
  "board_games_night.webp": {
    "base": "board_games_night",
    "w": 1080,
    "h": 1080,
    "tiers": [
      320,
      608,
      1080
    ],
    "srcKey": "1311696:1784148504520"
  },
  "lager_than_life2.webp": {
    "base": "lager_than_life2",
    "w": 1080,
    "h": 1920,
    "tiers": [
      320,
      608,
      1080
    ],
    "srcKey": "2895650:1784148598820"
  },
  "puma_bigpeach_hc_poster_edited.webp": {
    "base": "puma_bigpeach_hc_poster_edited",
    "w": 3300,
    "h": 5100,
    "tiers": [
      416,
      800,
      1600,
      3200
    ],
    "srcKey": "13707122:1784155038169"
  },
  "twin_night.webp": {
    "base": "twin_night",
    "w": 1080,
    "h": 1350,
    "tiers": [
      320,
      608,
      1080
    ],
    "srcKey": "1305396:1786563608156"
  },
  "trivia_flyer_1080x1350_color.webp": {
    "base": "trivia_flyer_1080x1350_color",
    "w": 1080,
    "h": 1350,
    "tiers": [
      320,
      608,
      1080
    ],
    "srcKey": "1051900:1786565909522"
  },
  "stammtisch-green.webp": {
    "base": "stammtisch-green",
    "w": 950,
    "h": 540,
    "tiers": [
      320,
      608,
      950
    ],
    "srcKey": "303448:1786567081032"
  },
  "stammtisch-1.webp": {
    "base": "stammtisch-1",
    "w": 950,
    "h": 540,
    "tiers": [
      320,
      608,
      950
    ],
    "srcKey": "284514:1786567070600"
  },
  "staff_show_digital_01.webp": {
    "base": "staff_show_digital_01",
    "w": 4500,
    "h": 5625,
    "tiers": [
      416,
      800,
      1600,
      3168
    ],
    "srcKey": "26931708:1786655043604"
  },
  "roast_dinner_card_1080x1920.webp": {
    "base": "roast_dinner_card_1080x1920",
    "w": 1080,
    "h": 1920,
    "tiers": [
      320,
      608,
      1080
    ],
    "srcKey": "1320768:1784154683841"
  },
  "ig_post_final_czechbeerdays.webp": {
    "base": "ig_post_final_czechbeerdays",
    "w": 2250,
    "h": 2813,
    "tiers": [
      352,
      704,
      1408,
      2250
    ],
    "srcKey": "7379422:1786736097972"
  },
  "ig_post_final_czechbeerdays_events.webp": {
    "base": "ig_post_final_czechbeerdays_events",
    "w": 2250,
    "h": 3100,
    "tiers": [
      352,
      704,
      1408,
      2250
    ],
    "srcKey": "1834230:1784148142842"
  },
  "Holiday_Hours_November.webp": {
    "base": "Holiday_Hours_November",
    "w": 1080,
    "h": 1920,
    "tiers": [
      256,
      480,
      960,
      1080
    ],
    "srcKey": "504564:1784147703092"
  },
  "Holiday_Hours_December.webp": {
    "base": "Holiday_Hours_December",
    "w": 1080,
    "h": 1920,
    "tiers": [
      256,
      480,
      960,
      1080
    ],
    "srcKey": "1083688:1784147734127"
  },
  "HC_Building.webp": {
    "base": "HC_Building",
    "w": 1834,
    "h": 1001,
    "tiers": [
      512,
      1024,
      1834
    ],
    "srcKey": "614490:1784147496887"
  },
  "FUNday_.webp": {
    "base": "FUNday_",
    "w": 2250,
    "h": 2813,
    "tiers": [
      320,
      608,
      1216,
      2250
    ],
    "srcKey": "3092166:1786737533442"
  },
  "Eurovision_Poster.webp": {
    "base": "Eurovision_Poster",
    "w": 3300,
    "h": 5100,
    "tiers": [
      384,
      736,
      1472,
      2944
    ],
    "srcKey": "11786494:1786738499434"
  },
  "boevenbartype.webp": {
    "base": "boevenbartype",
    "w": 1080,
    "h": 439,
    "tiers": [
      384,
      736,
      1080
    ],
    "srcKey": "88294:1784147623191"
  }
};
